"""Build the reviewer-facing PDF from the current editable case study Markdown.

The Markdown file is the source of truth. This exporter intentionally keeps the
PDF presentation-only: it does not read private credentials or the historical
JSON export. A small Markdown parser is used so the export stays dependency-light
and can be regenerated by a future maintainer with the repository's Python setup.
"""

from __future__ import annotations

import html
import re
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    LongTable,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    TableStyle,
)


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "deliverables" / "case-study-and-prd.md"
OUTPUT = ROOT / "deliverables" / "InterviewMate-Case-Study-and-Handoff.pdf"
PREVIEW_DIR = ROOT / "tmp" / "pdf-review"

GREEN = colors.HexColor("#184C38")
INK = colors.HexColor("#21342D")
MUTED = colors.HexColor("#56655E")
PALE = colors.HexColor("#F5F7F3")
PALE_GREEN = colors.HexColor("#E8F0EA")
GRID = colors.HexColor("#C9D6CC")


def plain(text: str) -> str:
    """Escape Markdown text and apply the small inline subset used in the report."""

    value = text.strip()
    value = value.replace("→", "->").replace("–", "-").replace("—", "-")
    value = value.replace("’", "'").replace("“", '"').replace("”", '"')
    value = escape(value)
    value = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", value)
    value = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<i>\1</i>", value)
    value = re.sub(r"`([^`]+)`", r'<font name="Courier">\1</font>', value)
    # Keep links readable in a PDF without printing long repository-relative URLs.
    value = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", value)
    return value


def paragraph(text: str, style: ParagraphStyle) -> Paragraph:
    return Paragraph(plain(text), style)


def table_from_rows(rows: list[list[str]], styles: dict[str, ParagraphStyle]):
    if not rows:
        return None
    column_count = max(len(row) for row in rows)
    normalized = [row + [""] * (column_count - len(row)) for row in rows]
    cell_rows = []
    for row_index, row in enumerate(normalized):
        cell_rows.append(
            [
                Paragraph(
                    plain(cell),
                    styles["table_head"] if row_index == 0 else styles["table_cell"],
                )
                for cell in row
            ]
        )

    available_width = A4[0] - (38 * mm)
    # Give narrative columns more room while keeping short ID/status columns usable.
    weights = [max(1, max(len(row[column]) for row in normalized)) for column in range(column_count)]
    total = sum(weights)
    widths = [max(42, available_width * weight / total) for weight in weights]
    width_total = sum(widths)
    if width_total > available_width:
        scale = available_width / width_total
        widths = [width * scale for width in widths]
    table = LongTable(cell_rows, colWidths=widths, repeatRows=1, hAlign="LEFT")
    commands = [
        ("BACKGROUND", (0, 0), (-1, 0), GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.45, GRID),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]
    for row_index in range(1, len(cell_rows)):
        if row_index % 2 == 0:
            commands.append(("BACKGROUND", (0, row_index), (-1, row_index), PALE_GREEN))
    table.setStyle(TableStyle(commands))
    return table


def parse_markdown(text: str):
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "SubmissionTitle", parent=base["Title"], fontName="Helvetica-Bold", fontSize=25,
            leading=30, textColor=INK, spaceAfter=12, alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "SubmissionSubtitle", parent=base["Normal"], fontName="Helvetica", fontSize=11,
            leading=16, textColor=GREEN, spaceAfter=10,
        ),
        "status": ParagraphStyle(
            "SubmissionStatus", parent=base["Normal"], fontName="Helvetica", fontSize=9,
            leading=14, textColor=MUTED, spaceAfter=16,
        ),
        "h1": ParagraphStyle(
            "SectionHeading", parent=base["Heading1"], fontName="Helvetica-Bold", fontSize=16,
            leading=20, textColor=INK, spaceBefore=18, spaceAfter=8, keepWithNext=True,
        ),
        "h2": ParagraphStyle(
            "Subheading", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=11.5,
            leading=15, textColor=GREEN, spaceBefore=12, spaceAfter=5, keepWithNext=True,
        ),
        "body": ParagraphStyle(
            "Body", parent=base["BodyText"], fontName="Helvetica", fontSize=9.2,
            leading=13.5, textColor=MUTED, spaceAfter=8, splitLongWords=True,
        ),
        "bullet": ParagraphStyle(
            "Bullet", parent=base["BodyText"], fontName="Helvetica", fontSize=9.2,
            leading=13.5, leftIndent=13, firstLineIndent=-8, textColor=MUTED, spaceAfter=4,
        ),
        "table_head": ParagraphStyle(
            "TableHead", parent=base["BodyText"], fontName="Helvetica-Bold", fontSize=7.4,
            leading=9.5, textColor=colors.white,
        ),
        "table_cell": ParagraphStyle(
            "TableCell", parent=base["BodyText"], fontName="Helvetica", fontSize=7.1,
            leading=9.3, textColor=INK, splitLongWords=True,
        ),
        "code": ParagraphStyle(
            "Code", parent=base["Code"], fontName="Courier", fontSize=6.8,
            leading=8.4, textColor=INK,
        ),
    }

    lines = text.replace("\r\n", "\n").split("\n")
    story = []
    index = 0
    seen_section = False
    while index < len(lines):
        raw = lines[index]
        stripped = raw.strip()
        if not stripped:
            index += 1
            continue

        if stripped.startswith("```"):
            language = stripped[3:].strip()
            code_lines = []
            index += 1
            while index < len(lines) and lines[index].strip() != "```":
                code_lines.append(lines[index].replace("->", "to").replace("-->", "to"))
                index += 1
            if index < len(lines):
                index += 1
            if code_lines:
                label = "Workflow diagram source" if language == "mermaid" else f"{language or 'Code'} example"
                story.append(Paragraph(label, styles["h2"]))
                story.append(Preformatted("\n".join(code_lines), styles["code"], maxLineLength=120))
                story.append(Spacer(1, 5))
            continue

        heading = re.match(r"^(#{1,3})\s+(.+)$", stripped)
        if heading:
            level, title = len(heading.group(1)), heading.group(2)
            if level == 1:
                story.append(paragraph(title, styles["title"]))
            elif level == 2:
                if seen_section is False and title.startswith("1. "):
                    story.append(PageBreak())
                seen_section = True
                story.append(paragraph(title, styles["h1"]))
            else:
                story.append(paragraph(title, styles["h2"]))
            index += 1
            continue

        if stripped.startswith("|") and index + 1 < len(lines) and re.match(r"^\s*\|?\s*:?-{3,}", lines[index + 1]):
            rows = []
            while index < len(lines) and lines[index].strip().startswith("|"):
                raw_cells = [cell.strip() for cell in lines[index].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{3,}:?", cell) for cell in raw_cells):
                    rows.append(raw_cells)
                index += 1
            table = table_from_rows(rows, styles)
            if table:
                story.append(Spacer(1, 3))
                story.append(table)
                story.append(Spacer(1, 9))
            continue

        list_match = re.match(r"^(?:[-*]|\d+\.)\s+(.+)$", stripped)
        if list_match:
            while index < len(lines):
                item = re.match(r"^(?:[-*]|\d+\.)\s+(.+)$", lines[index].strip())
                if not item:
                    break
                marker = "•" if not re.match(r"^\d+\.", lines[index].strip()) else lines[index].strip().split(" ", 1)[0]
                story.append(paragraph(f"{marker} {item.group(1)}", styles["bullet"]))
                index += 1
            continue

        # Combine a normal paragraph until the next structural boundary.
        paragraph_lines = [stripped]
        index += 1
        while index < len(lines):
            candidate = lines[index].strip()
            if not candidate or candidate.startswith("#") or candidate.startswith("|") or candidate.startswith("```") or re.match(r"^(?:[-*]|\d+\.)\s+", candidate):
                break
            paragraph_lines.append(candidate)
            index += 1
        combined = " ".join(paragraph_lines)
        if not story and len(combined) < 180:
            story.append(paragraph(combined, styles["subtitle"]))
        elif not story:
            story.append(paragraph(combined, styles["status"]))
        else:
            story.append(paragraph(combined, styles["body"]))

    return story


def draw_chrome(canvas, doc):
    width, height = A4
    canvas.saveState()
    canvas.setFillColor(PALE)
    canvas.rect(0, 0, width, height, fill=1, stroke=0)
    canvas.setFillColor(GREEN)
    canvas.rect(19 * mm, height - 17 * mm, 12 * mm, 1.2 * mm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(35 * mm, height - 17 * mm, "INTERVIEWMATE / PRODUCT SPRINT")
    canvas.setStrokeColor(GRID)
    canvas.line(19 * mm, 17 * mm, width - 19 * mm, 17 * mm)
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(19 * mm, 11 * mm, "Case study and engineering handoff / 11 September 2026")
    canvas.drawRightString(width - 19 * mm, 11 * mm, f"{doc.page}")
    canvas.restoreState()


def main() -> None:
    story = parse_markdown(SOURCE.read_text(encoding="utf-8"))
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    document = SimpleDocTemplate(
        str(OUTPUT), pagesize=A4, leftMargin=19 * mm, rightMargin=19 * mm,
        topMargin=25 * mm, bottomMargin=24 * mm,
        title="InterviewMate Case Study and Engineering Handoff",
        author="InterviewMate Product Sprint",
        subject="Current MVP case study and engineering handoff",
    )
    document.build(story, onFirstPage=draw_chrome, onLaterPages=draw_chrome)

    # Render page previews for visual QA, as required by the PDF workflow.
    import pypdfium2 as pdfium

    PREVIEW_DIR.mkdir(parents=True, exist_ok=True)
    pdf = pdfium.PdfDocument(str(OUTPUT))
    for page_number in range(len(pdf)):
        pdf[page_number].render(scale=1.35).to_pil().save(PREVIEW_DIR / f"page-{page_number + 1}.png")
    print(f"Built {len(pdf)} pages: {OUTPUT}")


if __name__ == "__main__":
    main()
